/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.cmu.courses.simplemr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class DFSFile implements org.apache.thrift.TBase<DFSFile, DFSFile._Fields>, java.io.Serializable, Cloneable, Comparable<DFSFile> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DFSFile");

  private static final org.apache.thrift.protocol.TField ID_FIELD_DESC = new org.apache.thrift.protocol.TField("id", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField CHUNK_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("chunkIds", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField REPLICAS_FIELD_DESC = new org.apache.thrift.protocol.TField("replicas", org.apache.thrift.protocol.TType.I32, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new DFSFileStandardSchemeFactory());
    schemes.put(TupleScheme.class, new DFSFileTupleSchemeFactory());
  }

  public long id; // required
  public String name; // required
  public List<Long> chunkIds; // required
  public int replicas; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ID((short)1, "id"),
    NAME((short)2, "name"),
    CHUNK_IDS((short)3, "chunkIds"),
    REPLICAS((short)4, "replicas");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ID
          return ID;
        case 2: // NAME
          return NAME;
        case 3: // CHUNK_IDS
          return CHUNK_IDS;
        case 4: // REPLICAS
          return REPLICAS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ID_ISSET_ID = 0;
  private static final int __REPLICAS_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ID, new org.apache.thrift.meta_data.FieldMetaData("id", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CHUNK_IDS, new org.apache.thrift.meta_data.FieldMetaData("chunkIds", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.REPLICAS, new org.apache.thrift.meta_data.FieldMetaData("replicas", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DFSFile.class, metaDataMap);
  }

  public DFSFile() {
  }

  public DFSFile(
    long id,
    String name,
    List<Long> chunkIds,
    int replicas)
  {
    this();
    this.id = id;
    setIdIsSet(true);
    this.name = name;
    this.chunkIds = chunkIds;
    this.replicas = replicas;
    setReplicasIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DFSFile(DFSFile other) {
    __isset_bitfield = other.__isset_bitfield;
    this.id = other.id;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetChunkIds()) {
      List<Long> __this__chunkIds = new ArrayList<Long>(other.chunkIds);
      this.chunkIds = __this__chunkIds;
    }
    this.replicas = other.replicas;
  }

  public DFSFile deepCopy() {
    return new DFSFile(this);
  }

  @Override
  public void clear() {
    setIdIsSet(false);
    this.id = 0;
    this.name = null;
    this.chunkIds = null;
    setReplicasIsSet(false);
    this.replicas = 0;
  }

  public long getId() {
    return this.id;
  }

  public DFSFile setId(long id) {
    this.id = id;
    setIdIsSet(true);
    return this;
  }

  public void unsetId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ID_ISSET_ID);
  }

  /** Returns true if field id is set (has been assigned a value) and false otherwise */
  public boolean isSetId() {
    return EncodingUtils.testBit(__isset_bitfield, __ID_ISSET_ID);
  }

  public void setIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ID_ISSET_ID, value);
  }

  public String getName() {
    return this.name;
  }

  public DFSFile setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public int getChunkIdsSize() {
    return (this.chunkIds == null) ? 0 : this.chunkIds.size();
  }

  public java.util.Iterator<Long> getChunkIdsIterator() {
    return (this.chunkIds == null) ? null : this.chunkIds.iterator();
  }

  public void addToChunkIds(long elem) {
    if (this.chunkIds == null) {
      this.chunkIds = new ArrayList<Long>();
    }
    this.chunkIds.add(elem);
  }

  public List<Long> getChunkIds() {
    return this.chunkIds;
  }

  public DFSFile setChunkIds(List<Long> chunkIds) {
    this.chunkIds = chunkIds;
    return this;
  }

  public void unsetChunkIds() {
    this.chunkIds = null;
  }

  /** Returns true if field chunkIds is set (has been assigned a value) and false otherwise */
  public boolean isSetChunkIds() {
    return this.chunkIds != null;
  }

  public void setChunkIdsIsSet(boolean value) {
    if (!value) {
      this.chunkIds = null;
    }
  }

  public int getReplicas() {
    return this.replicas;
  }

  public DFSFile setReplicas(int replicas) {
    this.replicas = replicas;
    setReplicasIsSet(true);
    return this;
  }

  public void unsetReplicas() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __REPLICAS_ISSET_ID);
  }

  /** Returns true if field replicas is set (has been assigned a value) and false otherwise */
  public boolean isSetReplicas() {
    return EncodingUtils.testBit(__isset_bitfield, __REPLICAS_ISSET_ID);
  }

  public void setReplicasIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __REPLICAS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case ID:
      if (value == null) {
        unsetId();
      } else {
        setId((Long)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case CHUNK_IDS:
      if (value == null) {
        unsetChunkIds();
      } else {
        setChunkIds((List<Long>)value);
      }
      break;

    case REPLICAS:
      if (value == null) {
        unsetReplicas();
      } else {
        setReplicas((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case ID:
      return Long.valueOf(getId());

    case NAME:
      return getName();

    case CHUNK_IDS:
      return getChunkIds();

    case REPLICAS:
      return Integer.valueOf(getReplicas());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case ID:
      return isSetId();
    case NAME:
      return isSetName();
    case CHUNK_IDS:
      return isSetChunkIds();
    case REPLICAS:
      return isSetReplicas();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof DFSFile)
      return this.equals((DFSFile)that);
    return false;
  }

  public boolean equals(DFSFile that) {
    if (that == null)
      return false;

    boolean this_present_id = true;
    boolean that_present_id = true;
    if (this_present_id || that_present_id) {
      if (!(this_present_id && that_present_id))
        return false;
      if (this.id != that.id)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_chunkIds = true && this.isSetChunkIds();
    boolean that_present_chunkIds = true && that.isSetChunkIds();
    if (this_present_chunkIds || that_present_chunkIds) {
      if (!(this_present_chunkIds && that_present_chunkIds))
        return false;
      if (!this.chunkIds.equals(that.chunkIds))
        return false;
    }

    boolean this_present_replicas = true;
    boolean that_present_replicas = true;
    if (this_present_replicas || that_present_replicas) {
      if (!(this_present_replicas && that_present_replicas))
        return false;
      if (this.replicas != that.replicas)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(DFSFile other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetId()).compareTo(other.isSetId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.id, other.id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetChunkIds()).compareTo(other.isSetChunkIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetChunkIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.chunkIds, other.chunkIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetReplicas()).compareTo(other.isSetReplicas());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReplicas()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.replicas, other.replicas);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("DFSFile(");
    boolean first = true;

    sb.append("id:");
    sb.append(this.id);
    first = false;
    if (!first) sb.append(", ");
    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("chunkIds:");
    if (this.chunkIds == null) {
      sb.append("null");
    } else {
      sb.append(this.chunkIds);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("replicas:");
    sb.append(this.replicas);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DFSFileStandardSchemeFactory implements SchemeFactory {
    public DFSFileStandardScheme getScheme() {
      return new DFSFileStandardScheme();
    }
  }

  private static class DFSFileStandardScheme extends StandardScheme<DFSFile> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, DFSFile struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.id = iprot.readI64();
              struct.setIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // CHUNK_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.chunkIds = new ArrayList<Long>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  long _elem10;
                  _elem10 = iprot.readI64();
                  struct.chunkIds.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setChunkIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // REPLICAS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.replicas = iprot.readI32();
              struct.setReplicasIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, DFSFile struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(ID_FIELD_DESC);
      oprot.writeI64(struct.id);
      oprot.writeFieldEnd();
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.chunkIds != null) {
        oprot.writeFieldBegin(CHUNK_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, struct.chunkIds.size()));
          for (long _iter11 : struct.chunkIds)
          {
            oprot.writeI64(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(REPLICAS_FIELD_DESC);
      oprot.writeI32(struct.replicas);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DFSFileTupleSchemeFactory implements SchemeFactory {
    public DFSFileTupleScheme getScheme() {
      return new DFSFileTupleScheme();
    }
  }

  private static class DFSFileTupleScheme extends TupleScheme<DFSFile> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DFSFile struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetId()) {
        optionals.set(0);
      }
      if (struct.isSetName()) {
        optionals.set(1);
      }
      if (struct.isSetChunkIds()) {
        optionals.set(2);
      }
      if (struct.isSetReplicas()) {
        optionals.set(3);
      }
      oprot.writeBitSet(optionals, 4);
      if (struct.isSetId()) {
        oprot.writeI64(struct.id);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetChunkIds()) {
        {
          oprot.writeI32(struct.chunkIds.size());
          for (long _iter12 : struct.chunkIds)
          {
            oprot.writeI64(_iter12);
          }
        }
      }
      if (struct.isSetReplicas()) {
        oprot.writeI32(struct.replicas);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DFSFile struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(4);
      if (incoming.get(0)) {
        struct.id = iprot.readI64();
        struct.setIdIsSet(true);
      }
      if (incoming.get(1)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.chunkIds = new ArrayList<Long>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            long _elem15;
            _elem15 = iprot.readI64();
            struct.chunkIds.add(_elem15);
          }
        }
        struct.setChunkIdsIsSet(true);
      }
      if (incoming.get(3)) {
        struct.replicas = iprot.readI32();
        struct.setReplicasIsSet(true);
      }
    }
  }

}

