/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package edu.cmu.courses.simplemr.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class SlaveWorkload implements org.apache.thrift.TBase<SlaveWorkload, SlaveWorkload._Fields>, java.io.Serializable, Cloneable, Comparable<SlaveWorkload> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SlaveWorkload");

  private static final org.apache.thrift.protocol.TField RUNNING_TASKS_FIELD_DESC = new org.apache.thrift.protocol.TField("runningTasks", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new SlaveWorkloadStandardSchemeFactory());
    schemes.put(TupleScheme.class, new SlaveWorkloadTupleSchemeFactory());
  }

  public long runningTasks; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RUNNING_TASKS((short)1, "runningTasks");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RUNNING_TASKS
          return RUNNING_TASKS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RUNNINGTASKS_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RUNNING_TASKS, new org.apache.thrift.meta_data.FieldMetaData("runningTasks", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SlaveWorkload.class, metaDataMap);
  }

  public SlaveWorkload() {
  }

  public SlaveWorkload(
    long runningTasks)
  {
    this();
    this.runningTasks = runningTasks;
    setRunningTasksIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SlaveWorkload(SlaveWorkload other) {
    __isset_bitfield = other.__isset_bitfield;
    this.runningTasks = other.runningTasks;
  }

  public SlaveWorkload deepCopy() {
    return new SlaveWorkload(this);
  }

  @Override
  public void clear() {
    setRunningTasksIsSet(false);
    this.runningTasks = 0;
  }

  public long getRunningTasks() {
    return this.runningTasks;
  }

  public SlaveWorkload setRunningTasks(long runningTasks) {
    this.runningTasks = runningTasks;
    setRunningTasksIsSet(true);
    return this;
  }

  public void unsetRunningTasks() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RUNNINGTASKS_ISSET_ID);
  }

  /** Returns true if field runningTasks is set (has been assigned a value) and false otherwise */
  public boolean isSetRunningTasks() {
    return EncodingUtils.testBit(__isset_bitfield, __RUNNINGTASKS_ISSET_ID);
  }

  public void setRunningTasksIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RUNNINGTASKS_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RUNNING_TASKS:
      if (value == null) {
        unsetRunningTasks();
      } else {
        setRunningTasks((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RUNNING_TASKS:
      return Long.valueOf(getRunningTasks());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RUNNING_TASKS:
      return isSetRunningTasks();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof SlaveWorkload)
      return this.equals((SlaveWorkload)that);
    return false;
  }

  public boolean equals(SlaveWorkload that) {
    if (that == null)
      return false;

    boolean this_present_runningTasks = true;
    boolean that_present_runningTasks = true;
    if (this_present_runningTasks || that_present_runningTasks) {
      if (!(this_present_runningTasks && that_present_runningTasks))
        return false;
      if (this.runningTasks != that.runningTasks)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(SlaveWorkload other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRunningTasks()).compareTo(other.isSetRunningTasks());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRunningTasks()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.runningTasks, other.runningTasks);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("SlaveWorkload(");
    boolean first = true;

    sb.append("runningTasks:");
    sb.append(this.runningTasks);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SlaveWorkloadStandardSchemeFactory implements SchemeFactory {
    public SlaveWorkloadStandardScheme getScheme() {
      return new SlaveWorkloadStandardScheme();
    }
  }

  private static class SlaveWorkloadStandardScheme extends StandardScheme<SlaveWorkload> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SlaveWorkload struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RUNNING_TASKS
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.runningTasks = iprot.readI64();
              struct.setRunningTasksIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SlaveWorkload struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(RUNNING_TASKS_FIELD_DESC);
      oprot.writeI64(struct.runningTasks);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SlaveWorkloadTupleSchemeFactory implements SchemeFactory {
    public SlaveWorkloadTupleScheme getScheme() {
      return new SlaveWorkloadTupleScheme();
    }
  }

  private static class SlaveWorkloadTupleScheme extends TupleScheme<SlaveWorkload> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SlaveWorkload struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRunningTasks()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRunningTasks()) {
        oprot.writeI64(struct.runningTasks);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SlaveWorkload struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.runningTasks = iprot.readI64();
        struct.setRunningTasksIsSet(true);
      }
    }
  }

}

